/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "./common";

export declare namespace AgentIdentityRegistry {
  export type AgentStruct = {
    walletAddress: AddressLike;
    name: string;
    dataCID: string;
    reputationScore: BigNumberish;
    totalEarnings: BigNumberish;
    totalRequests: BigNumberish;
    registrationTime: BigNumberish;
    isActive: boolean;
  };

  export type AgentStructOutput = [
    walletAddress: string,
    name: string,
    dataCID: string,
    reputationScore: bigint,
    totalEarnings: bigint,
    totalRequests: bigint,
    registrationTime: bigint,
    isActive: boolean
  ] & {
    walletAddress: string;
    name: string;
    dataCID: string;
    reputationScore: bigint;
    totalEarnings: bigint;
    totalRequests: bigint;
    registrationTime: bigint;
    isActive: boolean;
  };
}

export interface AgentIdentityRegistryInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "agentAddresses"
      | "agents"
      | "getAgent"
      | "getAgentCount"
      | "getAllAgents"
      | "owner"
      | "recordEarnings"
      | "registerAgent"
      | "updateDataCID"
      | "updateReputation"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "AgentRegistered"
      | "DataCIDUpdated"
      | "EarningsRecorded"
      | "ReputationUpdated"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "agentAddresses",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "agents", values: [AddressLike]): string;
  encodeFunctionData(
    functionFragment: "getAgent",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getAgentCount",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getAllAgents",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "recordEarnings",
    values: [AddressLike, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "registerAgent",
    values: [string, string]
  ): string;
  encodeFunctionData(
    functionFragment: "updateDataCID",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "updateReputation",
    values: [AddressLike, BigNumberish]
  ): string;

  decodeFunctionResult(
    functionFragment: "agentAddresses",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "agents", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "getAgent", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getAgentCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getAllAgents",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "recordEarnings",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "registerAgent",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "updateDataCID",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "updateReputation",
    data: BytesLike
  ): Result;
}

export namespace AgentRegisteredEvent {
  export type InputTuple = [agent: AddressLike, name: string, dataCID: string];
  export type OutputTuple = [agent: string, name: string, dataCID: string];
  export interface OutputObject {
    agent: string;
    name: string;
    dataCID: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace DataCIDUpdatedEvent {
  export type InputTuple = [agent: AddressLike, newCID: string];
  export type OutputTuple = [agent: string, newCID: string];
  export interface OutputObject {
    agent: string;
    newCID: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace EarningsRecordedEvent {
  export type InputTuple = [
    agent: AddressLike,
    amount: BigNumberish,
    requests: BigNumberish
  ];
  export type OutputTuple = [agent: string, amount: bigint, requests: bigint];
  export interface OutputObject {
    agent: string;
    amount: bigint;
    requests: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ReputationUpdatedEvent {
  export type InputTuple = [agent: AddressLike, newScore: BigNumberish];
  export type OutputTuple = [agent: string, newScore: bigint];
  export interface OutputObject {
    agent: string;
    newScore: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface AgentIdentityRegistry extends BaseContract {
  connect(runner?: ContractRunner | null): AgentIdentityRegistry;
  waitForDeployment(): Promise<this>;

  interface: AgentIdentityRegistryInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  agentAddresses: TypedContractMethod<[arg0: BigNumberish], [string], "view">;

  agents: TypedContractMethod<
    [arg0: AddressLike],
    [
      [string, string, string, bigint, bigint, bigint, bigint, boolean] & {
        walletAddress: string;
        name: string;
        dataCID: string;
        reputationScore: bigint;
        totalEarnings: bigint;
        totalRequests: bigint;
        registrationTime: bigint;
        isActive: boolean;
      }
    ],
    "view"
  >;

  getAgent: TypedContractMethod<
    [_agent: AddressLike],
    [AgentIdentityRegistry.AgentStructOutput],
    "view"
  >;

  getAgentCount: TypedContractMethod<[], [bigint], "view">;

  getAllAgents: TypedContractMethod<[], [string[]], "view">;

  owner: TypedContractMethod<[], [string], "view">;

  recordEarnings: TypedContractMethod<
    [_agent: AddressLike, _amount: BigNumberish, _requests: BigNumberish],
    [void],
    "nonpayable"
  >;

  registerAgent: TypedContractMethod<
    [_name: string, _dataCID: string],
    [void],
    "nonpayable"
  >;

  updateDataCID: TypedContractMethod<[_newCID: string], [void], "nonpayable">;

  updateReputation: TypedContractMethod<
    [_agent: AddressLike, _score: BigNumberish],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "agentAddresses"
  ): TypedContractMethod<[arg0: BigNumberish], [string], "view">;
  getFunction(
    nameOrSignature: "agents"
  ): TypedContractMethod<
    [arg0: AddressLike],
    [
      [string, string, string, bigint, bigint, bigint, bigint, boolean] & {
        walletAddress: string;
        name: string;
        dataCID: string;
        reputationScore: bigint;
        totalEarnings: bigint;
        totalRequests: bigint;
        registrationTime: bigint;
        isActive: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getAgent"
  ): TypedContractMethod<
    [_agent: AddressLike],
    [AgentIdentityRegistry.AgentStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "getAgentCount"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "getAllAgents"
  ): TypedContractMethod<[], [string[]], "view">;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "recordEarnings"
  ): TypedContractMethod<
    [_agent: AddressLike, _amount: BigNumberish, _requests: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "registerAgent"
  ): TypedContractMethod<
    [_name: string, _dataCID: string],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "updateDataCID"
  ): TypedContractMethod<[_newCID: string], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "updateReputation"
  ): TypedContractMethod<
    [_agent: AddressLike, _score: BigNumberish],
    [void],
    "nonpayable"
  >;

  getEvent(
    key: "AgentRegistered"
  ): TypedContractEvent<
    AgentRegisteredEvent.InputTuple,
    AgentRegisteredEvent.OutputTuple,
    AgentRegisteredEvent.OutputObject
  >;
  getEvent(
    key: "DataCIDUpdated"
  ): TypedContractEvent<
    DataCIDUpdatedEvent.InputTuple,
    DataCIDUpdatedEvent.OutputTuple,
    DataCIDUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "EarningsRecorded"
  ): TypedContractEvent<
    EarningsRecordedEvent.InputTuple,
    EarningsRecordedEvent.OutputTuple,
    EarningsRecordedEvent.OutputObject
  >;
  getEvent(
    key: "ReputationUpdated"
  ): TypedContractEvent<
    ReputationUpdatedEvent.InputTuple,
    ReputationUpdatedEvent.OutputTuple,
    ReputationUpdatedEvent.OutputObject
  >;

  filters: {
    "AgentRegistered(address,string,string)": TypedContractEvent<
      AgentRegisteredEvent.InputTuple,
      AgentRegisteredEvent.OutputTuple,
      AgentRegisteredEvent.OutputObject
    >;
    AgentRegistered: TypedContractEvent<
      AgentRegisteredEvent.InputTuple,
      AgentRegisteredEvent.OutputTuple,
      AgentRegisteredEvent.OutputObject
    >;

    "DataCIDUpdated(address,string)": TypedContractEvent<
      DataCIDUpdatedEvent.InputTuple,
      DataCIDUpdatedEvent.OutputTuple,
      DataCIDUpdatedEvent.OutputObject
    >;
    DataCIDUpdated: TypedContractEvent<
      DataCIDUpdatedEvent.InputTuple,
      DataCIDUpdatedEvent.OutputTuple,
      DataCIDUpdatedEvent.OutputObject
    >;

    "EarningsRecorded(address,uint256,uint256)": TypedContractEvent<
      EarningsRecordedEvent.InputTuple,
      EarningsRecordedEvent.OutputTuple,
      EarningsRecordedEvent.OutputObject
    >;
    EarningsRecorded: TypedContractEvent<
      EarningsRecordedEvent.InputTuple,
      EarningsRecordedEvent.OutputTuple,
      EarningsRecordedEvent.OutputObject
    >;

    "ReputationUpdated(address,uint256)": TypedContractEvent<
      ReputationUpdatedEvent.InputTuple,
      ReputationUpdatedEvent.OutputTuple,
      ReputationUpdatedEvent.OutputObject
    >;
    ReputationUpdated: TypedContractEvent<
      ReputationUpdatedEvent.InputTuple,
      ReputationUpdatedEvent.OutputTuple,
      ReputationUpdatedEvent.OutputObject
    >;
  };
}
