/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { AgentIdentityRegistry } from "./AgentIdentityRegistry";
export * as factories from "./factories";
export { AgentIdentityRegistry__factory } from "./factories/AgentIdentityRegistry__factory";
